import http from "http";
// import { app, port } from "./app.js";
// import fs from "fs";

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.end("node pag");
});

const port = 3001;

server.listen(port, () => {
  console.log(`server running at http://localhost:${port}`);
});

// function buildHtml(title, content) {
//   return `<!DOCTYPE html>
// <html lang="en">
// <head>
//   <meta charset="UTF-8">
//   <meta name="viewport" content="width=device-width, initial-scale=1.0">
//   <title>${title}</title>
// </head>
// <body>
//   <h1>${title}</h1>
//   <p>${content}</p>
// </body>
// </html>`;
// }

// const title = "Dynamic HTML Example";
// const content = "This content is generated by Node.js!";

// const htmlString = buildHtml(title, content);

// fs.writeFile("output.html", htmlString, (err) => {
//   if (err) {
//     console.error(err);
//   } else {
//     console.log("HTML file created successfully!");
//   }
// });

// import http from "http";
// import { app, port } from "./app.js";

// const server = http.createServer(app);

// server.listen(port, () => {
//   console.log(`server running at http://localhost:${port}`);
// });
